spring: 
  config:
    import: sm://  

dbname: "${sm://projects/the-bird-411104/secrets/dbname}"
dbusername: "${sm://projects/the-bird-411104/secrets/dbusername}"
dbpassword: "${sm://projects/the-bird-411104/secrets/dbpassword}"


