spring: 
  config:
    import: sm://  

#  cloud:
#    gcp:
#      credentials:
#        location: 'classpath:the-bird-411104-968841424385.json'

dbname: "${sm://projects/the-bird-411104/secrets/dbname}"
dbusername: "${sm://projects/the-bird-411104/secrets/dbusername}"
dbpassword: "${sm://projects/the-bird-411104/secrets/dbpassword}"


