spring: 
  config:
    import: sm://  

  cloud:
    gcp:
      credentials:
        location: classpath:the-bird-411104-049e2758b4cc.json
      project-id: the-bird-411104

dbname: "${sm://projects/the-bird-411104/secrets/dbname}"
dbusername: "${sm://projects/the-bird-411104/secrets/dbusername}"
dbpassword: "${sm://projects/the-bird-411104/secrets/dbpassword}"


