spring: 
  config:
    import: sm://  

  cloud:
    gcp:
      credentials:
        location: classpath:/the-bird-411104-2a8eb09db276.json
      project-id: the-bird-411104

dbname: "${sm://projects/the-bird-411104/secrets/dbname}"
dbusername: "${sm://projects/the-bird-411104/secrets/dbusername}"
dbpassword: "${sm://projects/the-bird-411104/secrets/dbpassword}"


